[theme]
base = "light"
primaryColor = "#553098"
backgroundColor = "#F3F1F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B2A3A"
font = "sans serif"
baseRadius = "0.75rem"
borderColor = "#DDD8E6"
showWidgetBorder = true

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
